weni-ai/vtex-webapp

src/components/DisableAgent.tsx
src/components/FeatureBox.tsx
src/locales/en.json
src/locales/es.json
src/locales/pt-BR.json
src/pages/Dashboard.tsx
src/services/agent.service.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds Disable Agent API Integration.

[HS-724] API Integration: Disable Agent

---

src/components/FeatureBox.tsx
src/components/settings/AbandonedCartActive.tsx
src/components/settings/SettingsContainer/SettingsContainer.tsx
src/components/settings/SettingsContainer/SettingsContext.tsx
src/locales/en.json
src/locales/es.json
src/locales/pt-BR.json
src/pages/Dashboard.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds Configure Agent API Integration.

[HS-723] API Integration: Configure Agent

---

src/pages/Dashboard.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
To identify the e-mail address on the login page, the VTEX App passes it through a query parameter.
* Passes user e-mail to Dash Weni.

[HS-779] Navigate to Weni: Passes E-mail as Query Param

---

src/api/channels/adapters.ts
src/components/FeatureBox.tsx
src/components/settings/SettingsContainer/SettingsContainer.tsx
src/interfaces/Store.ts
src/main.tsx
src/pages/Dashboard.tsx
src/pages/agent/AgentBuilder.tsx
src/pages/setup/useAgentBuilderSetup.ts
src/pages/setup/useUserSetup.ts
src/services/agent.service.ts
src/services/auth.service.ts
src/services/channel.service.ts
src/services/user.service.ts
src/store/projectSlice.ts
src/utils/VTEXFetch/index.ts
src/utils/facebook/login.ts
src/vite-env.d.ts

* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
As one of the technical debits, this PR removes all unnecessary any types to take better advantage of TypeScript's typing power in code development.
* Removes all unecessary any type in all the files.

[HS-890] Typings: Removes Unnecessary Any Type

---

public/pixel.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
In order to expose a static script within our architecture, the pixel.js script was created for application users to insert into their stores.
* Adds the `pixel.js` script.

[HS-917] Host Pixel Script

---

public/pixel.js
src/api/agents/adapters.ts
src/api/agents/requests.ts
src/components/AddAbandonedCart.tsx
src/components/FeatureBox.tsx
src/interfaces/Store.ts
src/pages/agent/AgentBuilder.tsx
src/pages/setup/useUserSetup.ts
src/store/projectSlice.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
This PR adds the functionality to save the store type and use this information to show the respective modal of the store type.
* Saves storeType and uses it to decide which modal to use;
* Updates the pixel script to the most up-to-date version.

[HS-977] Abandoned Cart Agent: Display the Integration Modal Properly

---

src/components/FeatureBox.tsx
src/services/agent.service.ts

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When an agent was being integrated, it wasn't showing the loading status correctly.
* Fixes agent integration loading status;
* Uses native loading status of the Shoreline Button component.

[HS-989] Agent Integration: Loading Status

---

src/components/AgentBox.tsx
src/interfaces/Store.ts
src/pages/Dashboard.tsx
src/services/agent.service.ts
src/store/projectSlice.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
In order to improve the user experience, this PR provides visual feedback on when the list of agents is being loaded.
* Adds Skeleton Loading for Agents List.

[HS-990] Agents List: Skeleton Loading for Agents

---

src/api/agents/adapters.ts
src/interfaces/Store.ts
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/Dashboard.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
When a template was rejected, no action was taken, with this PR the behavior of an agent with a rejected template will be to remove it so that the user can try to add the agent again.
* Adds `templateSynchronizationStatus` prop for Agents;
* Treats when template status is rejected.

[HS-1014] Template Status: Treatment for Rejected Templates

---

src/App.tsx
src/interfaces/Store.ts
src/pages/setup/useUserSetup.ts
src/store/projectSlice.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
In order to improve the visual feedback to the user when the App is having its first load, this PR adds a loading spinner to inform that the first loads are happening.
* Adds first loading logic;
* Adds visual loading spinner.

[HS-991] Initial Loading Spinner

---

src/api/channels/requests.ts
src/api/users/adapters.ts
src/api/users/requests.ts
src/pages/setup/useUserSetup.ts
src/services/agent.service.ts
src/services/channel.service.ts
src/services/user.service.ts

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fixes VTEXFetch calls with the valid typing.
* Adds typing for VTEXFetch calls.

[HS-1064] Fix Lint Errors

---

crowdin.yml

* * [ ] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Fix structure of `crowdin.yml` to match our current use pattern.

Fix crowdin.yml structure

---

docker/docker-entrypoint.sh
src/pages/Dashboard.tsx

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Previously there was a bug because the link to the Weni platform was fixed, and now with this PR it is considering the environment to redirect to the respective environment.
* Considers the environment to redirect to Weni Platform correctly.

[HS-1214] Redirect to Weni Platform According to the Environment

---

docker/docker-entrypoint.sh

Fix docker-entrypoint string
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- [Design File 1](link_to_design_file_1)

Fix docker-entrypoint string

---

src/interfaces/Store.ts
src/pages/agent/AgentBuilder.tsx
src/pages/setup/useAgentBuilderSetup.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Set the agent's prefilled information automatically.
* Sets up the agent info automatically.

[HS-1202] Agent Builder: Automatically Setup Agent

---

src/api/agents/adapters.ts
src/api/agents/requests.ts
src/components/AgentBox.tsx
src/components/DisableAgent.tsx
src/interfaces/Store.ts
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/Dashboard.tsx
src/services/agent.service.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
⚠️ Warning: this feature will undergo structural code improvements.
This PR adds support for passive agents within the agent gallery, their listing, integration and removal from the project.
* Adds support do passive agents from Nexus;
* Integrates passive agents;
* Disables passive agents.

[HS-1241] Passive Agents: List, Integrate and Disable Passive Agents

---

src/components/AgentBox.tsx

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Considers the agent uuid from the prop.

[HS-1254] Agents: Bug When Integrating Agent

---

src/api/agents/adapters.ts
src/components/AgentBox.tsx

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Limits Agent description to 3 lines.

[HS-1254] Agents: Limit Agent Description to 3 Lines

---

src/components/AgentBox.tsx

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Due to a Typescript error, this PR changes the properties of the style object to names that are acceptable and recognized by Typescript.
* Uses description as a separated var;
* Uses valid style attribute names.

[HS-1262] Agent Card: Description Text to 3 Lines

---

src/components/AgentMetrics.tsx
src/components/DashboardItem.tsx
src/pages/Dashboard.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
This PR redesigns the agent metrics component and prepare for the filters development.
* Redesigns Agent Metrics.
- [App - Agents Gallery - Home](https://www.figma.com/design/USjZMKo3y9WaQcHzxkvZUd/App---Agents-Gallery?node-id=84-4310&t=5ACVxb9E3D2qIYPo-4)

[HS-1265] Agent Metrics: Redesign

---

docker/docker-entrypoint.sh
package.json
src/main.tsx
src/pages/setup/useUserSetup.ts
src/plugins/growthbook.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
In order to prepare the project for the addition of feature flags, this PR adds GrowthBook for this management.
* Adds GrowthBook package and its env vars.

[HS-1300] GrowthBoook Implementation

---

src/App.tsx
src/components/AgentBox.tsx
src/components/TemplateCard.tsx
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/agent/Index.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
This PR adds the template card, a list of templates and associeated components and the agent's index page.
* Adds template card component and its associated components.
* Adds agent index page.
- [App - Agents Gallery - Template List](https://www.figma.com/design/USjZMKo3y9WaQcHzxkvZUd/App---Agents-Gallery?node-id=19-2608&m=dev)

[HS-1267] Template: List of Template Cards

---

package.json
src/api/agents/adapters.ts
src/api/agents/requests.ts
src/components/AgentBox.tsx
src/components/agent/ModalPassiveDetails.tsx
src/interfaces/Store.ts
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/Dashboard.tsx
src/services/agent.service.ts
src/store/projectSlice.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds Passive Agent Details Modal;
* Integration with WhatsApp Demo URL.
- [App - Agents Gallery - Passive Agent Details Modal](https://www.figma.com/design/USjZMKo3y9WaQcHzxkvZUd/App---Agents-Gallery?node-id=429-66834&m=dev)

[HS-1331] Agent: Passive Agent Details Modal

---

src/components/AgentBox.tsx
src/components/agent/modals/WhatsAppRequired.tsx
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/Channel.tsx
src/pages/agent/AgentBuilder.tsx
src/pages/setup/useUserSetup.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds possibility to skip WhatsApp integration on onboarding;
* Adds RequiredWhatsapp modal.

[HS-1321] Skip WhatsApp Integration on Onboarding

---

src/api/agents/adapters.ts
src/api/agents/requests.ts
src/components/AgentBox.tsx
src/components/agent/modals/Assign.tsx
src/components/agent/modals/AssignAbout.tsx
src/components/agent/modals/AssignCredentials.tsx
src/components/agent/modals/AssignSelectTemplate.tsx
src/components/agent/modals/AssignWhatsAppRequired.tsx
src/components/agent/modals/Gallery.tsx
src/index.d.ts
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/Dashboard.tsx
src/services/agent.service.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds Assignment process and its integration.
- [App - Agents Gallery - Integrar agente ativo](https://www.figma.com/design/USjZMKo3y9WaQcHzxkvZUd/App---Agents-Gallery?node-id=415-49695&m=dev)

[HS-1330] CLI Agents: Agent Assignment

---

src/App.tsx
src/api/agents/requests.ts
src/components/TemplateCard.tsx
src/interfaces/Store.ts
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/template/FormContent.tsx
src/pages/template/FormEssential.tsx
src/pages/template/Template.tsx
src/services/agent.service.ts
src/store/projectSlice.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Caches the assigned agents list;
* Populates template form page;
* Integrates template editing endpoint.
- [App - Agents Gallery - Edit template](https://www.figma.com/design/USjZMKo3y9WaQcHzxkvZUd/App---Agents-Gallery?node-id=216-13510&m=dev)

[HS-1335] CLI Agents: Update Template

---

src/pages/template/FormContent.tsx
src/pages/template/Template.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Possibilities the user to add header and footer to pre-approved templates.

[HS-1375] Templates: Possibility to Add Header and Footer to Pre-Approved Templates

---

src/components/AgentBox.tsx
src/pages/Dashboard.tsx
src/pages/agent/Index.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Removes temporary `agentDetailsPageAccess` and `agentGalleryModalAccess` feature flags.

[HS-1392] Feature Flag: Removes Temporary `agentDetailsPageAccess` and `agentGalleryModalAccess` Feature Flags

---

src/pages/agent/Index.tsx
src/pages/template/MessagePreview.tsx
src/services/agent.service.ts

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Makes long pooling for template list when there is a pending template;
* Shows break lines in Template Preview.

[HS-1371] Template List: Long Pooling

---

src/App.tsx
src/api/agents/requests.ts
src/api/channels/adapters.ts
src/api/channels/requests.ts
src/components/AgentBox.tsx
src/components/AgentMetrics.tsx
src/components/InputCopyToClipboard.tsx
src/components/TemplateCard.tsx
src/components/agent/ModalPassiveDetails.tsx
src/interfaces/Store.ts
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/Dashboard.tsx
src/pages/agent/Index.tsx
src/pages/setup/useUserSetup.ts
src/pages/template/FormContent.tsx
src/pages/template/Template.tsx
src/services/agent.service.ts
src/services/channel.service.ts
src/store/projectSlice.ts
src/store/userSlice.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds contact percentage in the agent settings tab;
* Adds its integration to API.
- [App - Agents Gallery - Assigned agent in test | Settings](https://www.figma.com/design/USjZMKo3y9WaQcHzxkvZUd/App---Agents-Gallery?node-id=240-19186&m=dev)

[HS-1426] Agent Settings: Contact Percentage

---

src/components/AgentBox.tsx
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/template/FormContent.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds view agent button in the Agent Card;
* Disables elements if it was prefilled previously in the Template Edit.
- [App - Agents Gallery - Home](https://www.figma.com/design/USjZMKo3y9WaQcHzxkvZUd/App---Agents-Gallery?node-id=115-7806&m=dev)

[HS-1391] Agent Card: View Agent Button

---

src/pages/template/Template.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Disables the save action if there are no changes.

[HS-1420] Template Edit: Save Action Only If There Is a Change

---

src/pages/template/FormContent.tsx

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Removes unused var.

[HS-1467] TypeScript Build Error

---

src/components/AgentBox.tsx
src/components/AgentMetrics.tsx
src/components/DisableAgent.tsx
src/components/TemplateCard.tsx
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/Dashboard.tsx
src/pages/template/MessagePreview.tsx

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Updates disable agents translations and styling;
* Treats when the template name is long on the template card;
* Changes active template status name to approved;
* Fixes spacing in home page;
* Adds a placeholder text on the message preview when the content text is empty.

[HS-1522] Design Review

---

src/api/agents/requests.ts
src/interfaces/Store.ts
src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/agent/Index.tsx
src/pages/template/FormEssential.tsx
src/pages/template/Template.tsx
src/services/agent.service.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds start condition edition support;
* Adds variables edition support.

[HS-1604] Template: Start Condition Edition

---

src/locales/en.json
src/locales/es-ES.json
src/locales/pt-BR.json
src/pages/template/FormContent.tsx
src/pages/template/FormVariables.tsx
src/pages/template/Template.tsx

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds variables validation: required field, missing variables in the content, and variables are not defined/created.
- [Design File 1](link_to_design_file_1)

[HS-1639] Template: Variables Validations

---

src/components/AgentMetrics.spec.tsx
src/components/AgentMetrics.tsx
src/utils/index.spec.ts
src/utils/index.ts

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds `AgentMetrics` component unit tests.

[HS-1623] Agent Metrics: Unit Tests

---

src/components/AgentBox.spec.tsx
src/components/AgentBox.tsx

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds `AgentBox` component unit tests.

[HS-1623] AgentBox: Unit Tests

---

src/components/agent/modals/Assign.spec.tsx
src/components/agent/modals/Assign.tsx

* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
* Adds `Agent Assign Modal` component unit tests.

[HS-1623] Agent Assign Modal: Unit Tests

---

src/api/agents/requests.ts
src/api/agentsSettings/requests.ts
src/api/channels/requests.ts
src/pages/template/Template.spec.tsx
src/pages/template/modals/Process.spec.tsx
src/services/agent.service.ts
src/services/channel.service.ts

* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
* Standardizations of the project's uuid parameter;
* Sends user email for assign and unassign agents endpoint.

[HS-1822] Standardization of the Project's Uuid Parameter

---

src/api/proxy.ts
src/api/users/adapters.ts
src/pages/setup/useUserSetup.ts
src/services/user.service.ts
src/utils/storage.ts

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* uses `moduleStorage` for consistent storage management.

[HS-1935] Module Federation: Consistent Storage Management
